from . import Canclebutton
from . import AdminPanelUz
from . import PhoneRU
from . import PhoneUZ
from . import PolUz
from . import PolRu
from . import RegionsUz
from . import RegionsRu
from . import ApplicationPageRu
from . import ApplicationPageUz
from . import PsychologistPageRu
from . import PsychologistPageUz
from . import TypeAppUz
from . import TypeAppRu
from . import SelectLanguage
